version: '3.7'
services:
#  web:
#    container_name: pet-api
#    image: mtakashimori/laravel
#    working_dir: /var/www/html/pet-api
#    command: php artisan serve --host=0.0.0.0 --port=80
#    volumes:
#      - .:/var/www/html/pet-api
#      # - ./docker/httpd.conf:/etc/apache2/sites-enabled/000-default.conf
#    entrypoint:  [
#      "/bin/sh",
#      "/var/www/html/pet-api/entrypoint.sh"
#    ]
#    stdin_open: true
#    tty: true
#    networks:
#      main:
#        aliases:
#          - web
  db:
    container_name: school-manager-db
    image: mariadb:10.4
    networks:
      main:
        aliases:
          - db

networks:
  main: